#!/bin/bash
###############################
## This is the biolock api interface.
## It calls the BiolockjAPI class.
###############################

main(){
	BLJ_JAR=${BLJ}/dist/BioLockJ.jar
	[ ! -f "${BLJ_JAR}" ] && exit_script "Error [ biolockj-api ]: BioLockJ Jar file \"${BLJ_JAR}\" not found."
	CMD="java -cp ${BLJ_JAR} biolockj.api.BioLockJ_API ${@}"
	[ ${#BIOLOCKJ_TEST_MODE} -gt 0 ] && echo "${BIOLOCKJ_TEST_MODE}$CMD" && exit
	eval $CMD
	statusCode=$?
    if [ ${statusCode} -ne 0 ]; then
    	display_help_without_java
    fi
}

# Display BioLockJ release version
display_version() {
	[ -f "${BLJ}/.version" ] && cat "${BLJ}/.version" && return
	echo "Missing ${BLJ}/.version"
}

display_help_without_java(){
	echo ""
	echo "BioLockJ API $(display_version) - UNCC Fodor Lab" 
	echo ""
	echo "Requires java (version 1.8 or higher)"
	echo "Current java version:"
	eval "java -version"
	echo ""
	echo "Requries BioLockJ (version 1.2.8 or higher)"
	echo "Current jar file version:"
	eval "java -jar $BLJ/dist/BioLockJ.jar --version"
	echo ""
	echo "Usage:"
	echo "biolockj-api <querry> [args...]"
	echo ""
	echo "Use biolockj-api without args to get help menu."
	echo ""
}

main $@
