#!/bin/bash
###############################################################################
##  This script manually resets current module and pipeline status.          ##
##  All modules numbered higher than the current module will also be reset.  ##
###############################################################################

BLJ_JAR=${BLJ}/dist/BioLockJ.jar
[ ! -f "${BLJ_JAR}" ] && exit_script "Error [ biolockj ]: BioLockJ Jar file \"${BLJ_JAR}\" not found."
java -jar ${BLJ_JAR} biolockj.launch.Reset ${PWD}
