#!/bin/bash

echo "The 'blj_complete' command is deprecated; and will be removed as of v1.4.0" 
echo "To manually mark a module as complete, cd to that module's folder and use:"
echo "touch biolockjComplete"
echo ""
