#!/bin/bash

# This script prints the Summary BioModule output of current pipeline.
# If the current directory is not a BioLockJ pipeline, print the summary of the most recent pipeline executed.


echo "The 'blj_summary' command is deprecated; and will be removed as of v1.4.0" 
echo "The following command is equivilent:"
echo 'cd $(last-pipeline); cat summary.txt'
echo ""



. $BLJ/script/blj_functions 

pipeline=$(most_recent_pipeline)
SUM=summary.txt
if [ -f $SUM ]; then
	echo "Print summary file: $SUM"
	cat $SUM
elif [ ${#pipeline} -gt 0 ]; then
	echo "Print summary file: $pipeline/$SUM"
	cat "$pipeline/$SUM"
else
	echo "No pipeline summary found in BLJ_PROJ: ${BLJ_PROJ}"
fi


echo ""
echo "The 'blj_summary' command is deprecated; and will be removed as of v1.4.0" 
echo "The following command is equivilent:"
echo 'cd $(last-pipeline); cat summary.txt'
echo ""
