#!/bin/bash

## This script returns the path to the most recent pipeline

## Ideal for:
## cd $(last-pipeline)
## ls `last-pipeline`

BLJ_JAR=${BLJ}/dist/BioLockJ.jar
[ ! -f "${BLJ_JAR}" ] && echo "Error [ last-pipeline ]: BioLockJ Jar file \"${BLJ_JAR}\" not found." && exit 1
java -cp ${BLJ_JAR} biolockj.api.BioLockJ_API last-pipeline
